import React, { useRef, useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import roomScene from '../assets/3d/lesso.glb';
import { a } from "@react-spring/three";


const Room = (props) => {
  const roomRef = useRef();
  const [isRotating, setIsRotating] = useState(false);
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(roomScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);
    lastX.current = event.clientX;
  };

  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();
    if (isRotating) {
      const delta = (event.clientX - lastX.current) / viewport.width;
      rotationSpeed.current = delta * 0.015 * Math.PI;
      lastX.current = event.clientX;
    }
  };

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.style.touchAction = 'none';

    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('pointerup', handlePointerUp);

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointermove', handlePointerMove);
      canvas.removeEventListener('pointerup', handlePointerUp);
    };
  }, [gl, isRotating]);

  useFrame(() => {
    if (!roomRef.current) return;

    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }
    }

    roomRef.current.rotation.y += rotationSpeed.current;
  });

  if (!nodes) {
    console.error('GLTF nodes not loaded.');
    return null;
  }

  
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

  return (
    <a.group ref={roomRef} {...props}>
       <mesh
        castShadow
        receiveShadow
        geometry={nodes.k2.geometry}
        material={materials['Material.015']}
        position={[2.263, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k3.geometry}
        material={materials['Material.015']}
        position={[2.541, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k5.geometry}
        material={materials['Material.015']}
        position={[3.088, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k6.geometry}
        material={materials['Material.015']}
        position={[3.373, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k7.geometry}
        material={materials['Material.015']}
        position={[3.649, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k8.geometry}
        material={materials['Material.015']}
        position={[3.649, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k9.geometry}
        material={materials['Material.015']}
        position={[3.373, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._k10.geometry}
        material={materials['Material.015']}
        position={[3.088, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k11.geometry}
        material={materials['Material.015']}
        position={[2.806, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k12.geometry}
        material={materials['Material.015']}
        position={[2.541, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k14.geometry}
        material={materials['Material.015']}
        position={[2.018, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k15.geometry}
        material={materials['Material.015']}
        position={[2.018, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k17.geometry}
        material={materials['Material.015']}
        position={[2.541, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k18.geometry}
        material={materials['Material.015']}
        position={[2.806, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k19.geometry}
        material={materials['Material.015']}
        position={[3.088, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k20.geometry}
        material={materials['Material.015']}
        position={[3.373, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k21.geometry}
        material={materials['Material.015']}
        position={[3.649, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['22'].geometry}
        material={materials['Material.015']}
        position={[2.263, 4.862, -4.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k22.geometry}
        material={materials['Material.015']}
        position={[2.018, 4.862, -4.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k23.geometry}
        material={materials['Material.015']}
        position={[3.649, 4.862, -4.069]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k24.geometry}
        material={materials['Material.015']}
        position={[3.373, 4.862, -4.069]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={materials['Material.028']}
        position={[4.663, 4.766, -4.408]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.scroll_wheel.geometry}
        material={materials['Material.040']}
        position={[4.66, 4.854, -4.566]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.006']}
        position={[2.594, 1.018, -2.466]}
        rotation={[-0.003, 1.524, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.006']}
        position={[2.309, 1.039, -2.663]}
        rotation={[-3.141, -0.195, 3.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials['Material.003']}
        position={[2.283, 4.42, -1.611]}
        rotation={[-1.563, 0.015, -0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials['Material.004']}
        position={[-0.687, 5.461, -5.624]}
        rotation={[1.024, 0.985, 0.024]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials['Material.004']}
        position={[-0.623, 5.447, -5.624]}
        rotation={[-1.698, 1.225, 2.852]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials['Material.004']}
        position={[-0.57, 5.504, -5.65]}
        rotation={[-1.799, 0.045, 3.133]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials['Material.004']}
        position={[-0.593, 5.559, -5.68]}
        rotation={[-1.608, -0.891, -2.898]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials['Material.004']}
        position={[-0.675, 5.563, -5.692]}
        rotation={[0.795, -0.984, -0.451]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials['Material.004']}
        position={[-0.715, 5.509, -5.665]}
        rotation={[1.636, -0.115, -0.076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.027']}
        position={[-0.643, 5.509, -5.66]}
        rotation={[1.045, 0.803, 0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve002.geometry}
        material={materials['Material.021']}
        position={[-0.585, 5.041, -5.674]}
        rotation={[0.007, -0.148, -1.457]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve003.geometry}
        material={nodes.BézierCurve003.material}
        position={[-0.585, 5.041, -5.674]}
        rotation={[0.007, -0.148, -1.457]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve004.geometry}
        material={materials['Material.021']}
        position={[-0.439, 5.24, -5.858]}
        rotation={[0.007, -0.148, -1.457]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve005.geometry}
        material={materials['Material.021']}
        position={[-0.241, 5.155, -5.761]}
        rotation={[0.007, 0.328, -1.461]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials['Material.004']}
        position={[-0.611, 5.779, -5.877]}
        rotation={[1.636, -0.113, -0.076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials['Material.004']}
        position={[-0.567, 5.832, -5.903]}
        rotation={[0.798, -0.981, -0.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials['Material.004']}
        position={[-0.483, 5.826, -5.892]}
        rotation={[-1.605, -0.898, -2.895]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials['Material.004']}
        position={[-0.46, 5.772, -5.863]}
        rotation={[-1.798, 0.038, 3.133]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials['Material.004']}
        position={[-0.518, 5.717, -5.835]}
        rotation={[-1.699, 1.222, 2.854]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials['Material.004']}
        position={[-0.582, 5.73, -5.836]}
        rotation={[1.023, 0.987, 0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials['Material.027']}
        position={[-0.536, 5.778, -5.872]}
        rotation={[1.044, 0.807, 0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials['Material.004']}
        position={[-0.301, 5.586, -5.666]}
        rotation={[1.022, 0.993, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials['Material.004']}
        position={[-0.242, 5.573, -5.665]}
        rotation={[-1.7, 1.219, 2.856]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={materials['Material.004']}
        position={[-0.185, 5.629, -5.693]}
        rotation={[-1.797, 0.035, 3.133]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials['Material.004']}
        position={[-0.203, 5.683, -5.723]}
        rotation={[-1.6, -0.907, -2.891]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials['Material.004']}
        position={[-0.28, 5.686, -5.735]}
        rotation={[0.809, -0.969, -0.436]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials['Material.004']}
        position={[-0.325, 5.633, -5.708]}
        rotation={[1.638, -0.104, -0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials['Material.027']}
        position={[-0.255, 5.633, -5.703]}
        rotation={[1.044, 0.814, 0.016]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.005']}
        position={[1.896, 3.135, -1.559]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials['Material.005']}
        position={[2.716, 3.135, -1.559]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane051.geometry}
        material={materials['Material.032']}
        position={[-3.035, 0.158, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials['Material.014']}
        position={[-3.035, -0.162, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials['Material.023']}
        position={[-3.035, -0.162, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane054.geometry}
        material={materials['Material.023']}
        position={[-3.035, -1.205, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane055.geometry}
        material={materials['Material.014']}
        position={[-3.035, -1.205, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane056.geometry}
        material={materials['Material.014']}
        position={[-3.035, -2.269, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane057.geometry}
        material={materials['Material.023']}
        position={[-3.035, -2.269, -4.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane060.geometry}
        material={materials['Material.011']}
        position={[-3.909, 7.479, -6.287]}
        rotation={[1.579, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials['Material.015']}
        position={[-3.902, 9.822, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.015']}
        position={[-3.902, 9.822, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[-3.902, 9.822, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials['Material.015']}
        position={[-1.549, 9.822, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials['Material.015']}
        position={[-1.549, 9.822, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane061.geometry}
        material={materials['Floor Plank']}
        position={[-2.744, 9.977, -5.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials['Material.015']}
        position={[-1.549, 8.277, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[-1.549, 8.277, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[-3.141, 8.277, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials['Material.015']}
        position={[-3.141, 8.277, -5.738]}
        rotation={[1.561, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane062.geometry}
        material={materials['Floor Plank']}
        position={[-2.325, 8.32, -5.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={materials['Material.015']}
        position={[-3.796, 9.215, -5.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane064.geometry}
        material={materials['Material.018']}
        position={[3.092, 0.582, -5.552]}
        rotation={[0, 0.868, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane065.geometry}
        material={materials['Material.023']}
        position={[3.34, 0.681, -5.85]}
        rotation={[0, 0.868, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={nodes.Plane066.material}
        position={[0.587, -0.34, -5.437]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials['Material.016']}
        position={[0.737, 0.16, -4.995]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane068.geometry}
        material={materials['Material.033']}
        position={[0.737, 0.118, -4.995]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={nodes.Plane069.material}
        position={[0.711, 0.314, -4.358]}
        rotation={[1.535, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane070.geometry}
        material={nodes.Plane070.material}
        position={[0.711, 0.314, -4.358]}
        rotation={[1.535, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={nodes.Plane071.material}
        position={[0.737, 0.042, -4.995]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane072.geometry}
        material={nodes.Plane072.material}
        position={[0.737, 0.085, -4.995]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane073.geometry}
        material={materials['Material.033']}
        position={[0.737, 0.737, -4.995]}
        rotation={[0, -0.511, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane074.geometry}
        material={materials['Material.016']}
        position={[0.737, 0.78, -4.995]}
        rotation={[0, -0.511, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials['Material.016']}
        position={[0.737, 1.253, -4.995]}
        rotation={[0, 0.249, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane076.geometry}
        material={materials['Material.033']}
        position={[0.737, 1.21, -4.995]}
        rotation={[0, 0.249, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor004.geometry}
        material={materials['Material.037']}
        position={[2.874, 6.689, -5.597]}
        scale={1.163}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k16002.geometry}
        material={materials['Material.015']}
        position={[2.263, 4.862, -4.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k13001.geometry}
        material={materials['Material.015']}
        position={[2.263, 4.862, -4.526]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k4001.geometry}
        material={materials['Material.015']}
        position={[2.806, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert008.geometry}
        material={materials['Material.028']}
        position={[-0.806, 5.183, -4.455]}
        rotation={[2.3, -1.018, 2.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert009.geometry}
        material={materials['Material.028']}
        position={[-0.51, 5.343, -4.874]}
        rotation={[-0.887, 1.024, 0.809]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials['Material.028']}
        position={[-0.37, 5.133, -4.937]}
        rotation={[-0.817, 1.032, 0.924]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials['Material.028']}
        position={[-0.387, 5.119, -4.875]}
        rotation={[-0.817, 1.031, 0.924]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials['Material.028']}
        position={[-0.451, 5.266, -4.863]}
        rotation={[-1.042, 0.838, 1.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane063.geometry}
        material={materials['Material.026']}
        position={[-0.033, 4.753, -3.796]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane077.geometry}
        material={materials['Material.009']}
        position={[-1.814, 10.637, -6.094]}
        rotation={[2.764, -1.539, -1.627]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={materials['Material.038']}
        position={[-2.825, 8.92, -5.406]}
        rotation={[-1.862, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials['Material.012']}
        position={[-1.649, 8.747, -5.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials['Material.012']}
        position={[-1.649, 8.747, -5.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube.geometry}
        material={materials['Material.021']}
        position={[-1.657, 9.243, -5.464]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube004.geometry}
        material={materials['Material.021']}
        position={[-1.454, 9.119, -5.487]}
        rotation={[-0.128, -0.055, -0.738]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane058.geometry}
        material={materials['Material.027']}
        position={[-3.308, 3.874, -5.519]}
        rotation={[0, -0.554, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane059.geometry}
        material={materials['Material.002']}
        position={[-3.283, 3.874, -5.504]}
        rotation={[0, -0.554, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane079.geometry}
        material={materials['Material.002']}
        position={[-3.191, 10.273, -5.586]}
        rotation={[0, -1.378, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane080.geometry}
        material={nodes.Plane080.material}
        position={[-3.195, 10.273, -5.607]}
        rotation={[0, -1.378, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane081.geometry}
        material={materials['Material.033']}
        position={[-3.205, 10.697, -5.593]}
        rotation={[0.03, -1.17, 1.919]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane082.geometry}
        material={materials['Material.026']}
        position={[-3.293, 4.235, -5.5]}
        rotation={[0, -1.37, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane083.geometry}
        material={nodes.Plane083.material}
        position={[1.845, 5.487, -5.772]}
        rotation={[0, -1.37, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane084.geometry}
        material={materials['Material.013']}
        position={[-2.034, 3.901, -4.666]}
        rotation={[0, 0.412, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials.Material}
        position={[-2.325, 4.55, -4.537]}
        rotation={[-2.317, -0.267, -1.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={materials['Material.028']}
        position={[-1.767, 4.55, -4.781]}
        rotation={[-2.317, -0.267, -1.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.027']}
        position={[-2.009, 4.878, -4.957]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert004.geometry}
        material={nodes.Vert004.material}
        position={[-2.024, 4.116, -4.983]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert005.geometry}
        material={nodes.Vert005.material}
        position={[-2.024, 4.116, -4.983]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['Material.033']}
        position={[-1.858, 4.907, -4.974]}
        rotation={[2.69, -1.48, 2.653]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['Material.033']}
        position={[-2.018, 4.902, -4.822]}
        rotation={[Math.PI, -0.028, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['Material.033']}
        position={[-2.141, 4.894, -4.995]}
        rotation={[-0.231, 1.435, 0.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['Material.033']}
        position={[-2.007, 4.897, -5.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-2.009, 4.878, -4.957]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert006.geometry}
        material={nodes.Vert006.material}
        position={[-2.024, 4.116, -4.64]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['Material.033']}
        position={[-1.858, 4.907, -4.631]}
        rotation={[2.69, -1.48, 2.653]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials['Material.033']}
        position={[-2.018, 4.902, -4.479]}
        rotation={[Math.PI, -0.028, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials['Material.033']}
        position={[-2.141, 4.894, -4.652]}
        rotation={[-0.231, 1.435, 0.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials['Material.033']}
        position={[-2.007, 4.897, -4.746]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials['Material.027']}
        position={[-2.009, 4.878, -4.614]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert007.geometry}
        material={nodes.Vert007.material}
        position={[-1.869, 4.116, -4.309]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials['Material.027']}
        position={[-1.854, 4.878, -4.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials['Material.033']}
        position={[-1.852, 4.897, -4.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials['Material.033']}
        position={[-1.986, 4.894, -4.321]}
        rotation={[-0.231, 1.435, 0.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Material.033']}
        position={[-1.863, 4.902, -4.148]}
        rotation={[Math.PI, -0.028, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['Material.033']}
        position={[-1.703, 4.907, -4.3]}
        rotation={[2.69, -1.48, 2.653]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert010.geometry}
        material={nodes.Vert010.material}
        position={[-2.292, 4.116, -4.783]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials['Material.027']}
        position={[-2.277, 4.878, -4.756]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert011.geometry}
        material={nodes.Vert011.material}
        position={[-2.111, 4.137, -4.492]}
        rotation={[0.21, -0.11, -0.118]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        position={[-1.856, 4.879, -4.296]}
        rotation={[-2.546, -1.363, -2.793]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['Material.033']}
        position={[-2.032, 4.865, -4.162]}
        rotation={[-2.929, 0.082, -3.024]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Material.033']}
        position={[-2.135, 4.91, -4.342]}
        rotation={[0.552, 1.313, -0.301]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials['Material.033']}
        position={[-1.992, 4.913, -4.422]}
        rotation={[0.21, -0.11, -0.118]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials['Material.027']}
        position={[-2.011, 4.868, -4.297]}
        rotation={[0.21, -0.11, -0.118]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane085.geometry}
        material={materials['Material.023']}
        position={[3.953, 0.69, -5.384]}
        rotation={[0, 0.467, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane086.geometry}
        material={materials['Material.018']}
        position={[3.608, 0.591, -5.207]}
        rotation={[0, 0.467, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane087.geometry}
        material={nodes.Plane087.material}
        position={[0.868, 1.34, -4.496]}
        rotation={[1.539, 0.006, 2.953]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={nodes.Plane031.material}
        position={[0.311, 0.937, -4.482]}
        rotation={[1.542, -0.016, -2.618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane088.geometry}
        material={materials['Material.002']}
        position={[-0.033, 4.753, -3.796]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane089.geometry}
        material={materials['Material.002']}
        position={[-0.033, 4.753, -3.717]}
        rotation={[-0.172, 0.115, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane090.geometry}
        material={materials['Material.002']}
        position={[-0.128, 4.777, -3.915]}
        rotation={[0.22, -0.524, -0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane092.geometry}
        material={materials['Floor Plank']}
        position={[7.094, 8.671, -3.809]}
        rotation={[0, 0, -1.568]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.038']}
        position={[2.174, 10.332, -6.256]}
        rotation={[-1.56, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane093.geometry}
        material={materials['Material.012']}
        position={[5.457, 6.742, -6.361]}
        rotation={[1.676, -0.613, 0.119]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane094.geometry}
        material={materials['Material.012']}
        position={[4.89, 6.742, -6.361]}
        rotation={[1.568, 0.56, -0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane095.geometry}
        material={materials['Material.012']}
        position={[5.179, 6.173, -6.361]}
        rotation={[1.568, 0.56, -0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane097.geometry}
        material={materials['Material.012']}
        position={[5.541, 5.692, -6.361]}
        rotation={[1.568, 0.56, -0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane098.geometry}
        material={materials['Material.012']}
        position={[5.144, 7.323, -6.361]}
        rotation={[1.568, 0.56, -0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane096.geometry}
        material={materials['Material.034']}
        position={[2.177, 10.591, -6.237]}
        rotation={[1.571, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane099.geometry}
        material={nodes.Plane099.material}
        position={[2.177, 10.591, -6.237]}
        rotation={[1.571, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane100.geometry}
        material={materials['Material.034']}
        position={[2.277, 10.393, -6.245]}
        rotation={[-1.72, -0.539, 2.926]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.034']}
        position={[2.188, 10.335, -6.248]}
        rotation={[1.479, -0.205, 0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane101.geometry}
        material={materials.Material}
        position={[1.109, 0.61, 4.076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane102.geometry}
        material={materials.Material}
        position={[1.622, 0.856, 3.543]}
        rotation={[0, 0, 0.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert003.geometry}
        material={materials['Material.002']}
        position={[-3.925, 7.871, -5.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.037']}
        position={[-1.832, 7.233, -5.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.009']}
        position={[6.159, 4, 1.691]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[6.089, 3.929, 2.153]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 1.481]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 1.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 2.522]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 2.872]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 3.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 3.891]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 4.241]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 4.902]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials['Material.001']}
        position={[6.225, 4.175, 5.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={nodes.Cube048.material}
        position={[6.225, 4.175, 5.304]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.002']}
        position={[6.017, 0.367, 3.936]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane091.geometry}
        material={materials['Material.013']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane105.geometry}
        material={materials['Floor Plank']}
        position={[4.989, 10.725, -6.696]}
        rotation={[-1.568, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane106.geometry}
        material={materials['Material.025']}
        position={[0.756, 9.185, -5.809]}
        rotation={[Math.PI / 2, 0.581, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials['Material.035']}
        position={[0.75, 9.185, -5.731]}
        rotation={[3.142, 0, -2.151]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane104.geometry}
        material={materials['Material.025']}
        position={[4.74, 9.185, -5.809]}
        rotation={[Math.PI / 2, 0.581, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials['Material.035']}
        position={[4.734, 9.185, -5.731]}
        rotation={[3.142, 0, -2.151]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane107.geometry}
        material={materials['Material.012']}
        position={[0.725, 6.959, -6.361]}
        rotation={[1.568, -0.514, -0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane109.geometry}
        material={materials['Material.012']}
        position={[-0.269, 6.38, -6.361]}
        rotation={[1.568, -0.514, -0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane110.geometry}
        material={materials['Material.012']}
        position={[0.092, 6.906, -6.361]}
        rotation={[1.568, -0.514, -0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane111.geometry}
        material={materials['Material.012']}
        position={[0.362, 6.407, -6.361]}
        rotation={[-2.196, -1.424, 2.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane108.geometry}
        material={materials['Material.002']}
        position={[1.848, 5.487, -5.757]}
        rotation={[0, -1.37, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.015']}
        position={[6.477, 9.302, -5.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials['Material.009']}
        position={[6.477, 9.302, -5.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials['Material.038']}
        position={[6.575, 9.657, -5.261]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={materials['Material.002']}
        position={[6.575, 9.657, -5.261]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={nodes.Cube055.material}
        position={[6.575, 9.657, -5.261]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={materials['Material.002']}
        position={[6.575, 9.657, -5.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert012.geometry}
        material={materials['Material.002']}
        position={[6.216, 9.25, -5.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane103.geometry}
        material={materials['Material.012']}
        position={[0.124, 5.767, -6.361]}
        rotation={[1.568, -0.514, -0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane113.geometry}
        material={materials['Material.012']}
        position={[0.658, 7.569, -6.292]}
        rotation={[1.568, -0.514, -0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane114.geometry}
        material={materials['Material.007']}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane115.geometry}
        material={materials['Material.008']}
        position={[7.259, 8.184, 1.687]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane116.geometry}
        material={materials['Floor Plank']}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane117.geometry}
        material={materials['Material.033']}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane133.geometry}
        material={materials['Material.033']}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane134.geometry}
        material={nodes.Plane134.material}
        position={[6.782, 6.36, -0.373]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane135.geometry}
        material={materials['Material.033']}
        position={[6.782, 6.245, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane136.geometry}
        material={nodes.Plane136.material}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane137.geometry}
        material={materials['Material.033']}
        position={[6.782, 6.145, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane138.geometry}
        material={materials['Material.033']}
        position={[6.782, 6.037, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane139.geometry}
        material={materials['Material.033']}
        position={[7.031, 9.902, -0.375]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane140.geometry}
        material={materials['Material.033']}
        position={[7.031, 10.024, -0.375]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane141.geometry}
        material={materials['Material.033']}
        position={[7.031, 10.141, -0.375]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane142.geometry}
        material={materials['Material.033']}
        position={[7.031, 10.248, -0.375]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pot002.geometry}
        material={materials['Material.033']}
        position={[-0.356, 4.661, -5.723]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert013.geometry}
        material={nodes.Vert013.material}
        position={[-2.292, 4.116, -4.783]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Room002.geometry}
        material={materials['Material.007']}
        position={[0.725, 6.34, -0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={materials['Material.033']}
        position={[-2.126, 4.907, -4.774]}
        rotation={[2.69, -1.48, 2.653]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={materials['Material.033']}
        position={[-2.286, 4.902, -4.622]}
        rotation={[Math.PI, -0.028, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials['Material.033']}
        position={[-2.409, 4.894, -4.794]}
        rotation={[-0.231, 1.435, 0.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={materials['Material.033']}
        position={[-2.275, 4.897, -4.889]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        position={[-2.277, 4.878, -4.756]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert014.geometry}
        material={nodes.Vert014.material}
        position={[1.181, 1.684, 3.369]}
        rotation={[-0.175, 0.085, 0.102]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials['Material.027']}
        position={[1.12, 2.438, 3.268]}
        rotation={[-0.175, 0.085, 0.102]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063.geometry}
        material={materials['Material.015']}
        position={[1.109, 2.433, 3.135]}
        rotation={[-0.175, 0.085, 0.102]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials['Material.015']}
        position={[0.985, 2.435, 3.241]}
        rotation={[-1.394, 1.43, 1.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials['Material.015']}
        position={[1.12, 2.483, 3.397]}
        rotation={[2.964, -0.113, 3.039]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials['Material.015']}
        position={[1.266, 2.475, 3.231]}
        rotation={[1.382, -1.429, 1.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert015.geometry}
        material={nodes.Vert015.material}
        position={[1.099, 1.669, 3.469]}
        rotation={[0.154, -0.093, -0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials['Material.015']}
        position={[1.326, 2.43, 3.618]}
        rotation={[-2.758, -1.391, -2.948]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials['Material.015']}
        position={[1.153, 2.417, 3.754]}
        rotation={[-2.985, 0.065, -3.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials['Material.015']}
        position={[1.046, 2.447, 3.573]}
        rotation={[0.369, 1.34, -0.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials['Material.015']}
        position={[1.188, 2.452, 3.492]}
        rotation={[0.154, -0.093, -0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials['Material.027']}
        position={[1.172, 2.413, 3.619]}
        rotation={[0.154, -0.093, -0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube005.geometry}
        material={materials['Material.002']}
        position={[0.637, 0.984, 4.481]}
        rotation={[0, -1.344, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials['Material.040']}
        position={[0.757, 1.633, 4.587]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials['Material.040']}
        position={[0.757, 1.633, 4.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube003.geometry}
        material={materials['Material.021']}
        position={[1.833, 1.637, 4.489]}
        rotation={[-0.128, -0.055, -0.738]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube006.geometry}
        material={materials['Material.021']}
        position={[1.6, 1.781, 4.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.009']}
        position={[1.608, 1.207, 4.522]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.009']}
        position={[1.608, 1.207, 4.522]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane143.geometry}
        material={materials['Material.018']}
        position={[6.474, 0.112, -1.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.025']}
        position={[6.461, 1.765, -1.813]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials.SVGMat}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={materials.SVGMat}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={materials.SVGMat}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve004.geometry}
        material={materials['SVGMat.001']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005.geometry}
        material={materials['SVGMat.001']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve006.geometry}
        material={materials['SVGMat.001']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007.geometry}
        material={materials['SVGMat.001']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane144.geometry}
        material={materials['Floor Plank']}
        position={[-5.286, 11.942, -6.695]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane145.geometry}
        material={materials['Floor Plank']}
        position={[-5.182, 11.97, -6.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Room003.geometry}
        material={materials['Floor Plank']}
        position={[0.725, 6.34, -0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane146.geometry}
        material={materials['Floor Plank.001']}
        position={[6.778, 5.269, 1.665]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve009.geometry}
        material={materials['SVGMat.002']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve010.geometry}
        material={materials['SVGMat.002']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve011.geometry}
        material={materials['SVGMat.002']}
        position={[1.501, -1.219, -0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane152.geometry}
        material={materials['Material.019']}
        position={[6.782, 6.36, -0.375]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_surface.geometry}
        material={materials['Material.015']}
        position={[2.93, 4.601, -5.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Legs.geometry}
        material={materials['Material.016']}
        position={[6.311, 4.52, -5.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_base.geometry}
        material={materials['Material.016']}
        position={[6.311, 0.366, -5.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moniter_table.geometry}
        material={materials['Material.026']}
        position={[0.814, 4.741, -5.924]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor_stand.geometry}
        material={materials['Material.003']}
        position={[2.871, 5.405, -5.823]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_pad.geometry}
        material={materials['Material.012']}
        position={[2.882, 4.568, -4.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Key_board.geometry}
        material={materials['Material.028']}
        position={[2.854, 4.808, -4.423]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.k1.geometry}
        material={materials['Material.015']}
        position={[2.018, 4.862, -4.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.018']}
        position={[0.581, 4.633, -4.777]}
        rotation={[-0.003, 0.106, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Calender_ring_1.geometry}
        material={materials.Material}
        position={[0.14, 5.054, -4.736]}
        rotation={[0.235, 0.11, 1.612]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Calender_ring_2.geometry}
        material={materials.Material}
        position={[0.418, 5.073, -4.763]}
        rotation={[0.235, 0.11, 1.612]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Calender_ring_3.geometry}
        material={materials.Material}
        position={[0.721, 5.093, -4.793]}
        rotation={[0.235, 0.11, 1.612]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Calender_ring_4.geometry}
        material={materials.Material}
        position={[1.006, 5.111, -4.821]}
        rotation={[0.235, 0.11, 1.612]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[6.087, 4.747, -4.801]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Material.012']}
        position={[-0.606, 4.761, -4.53]}
        rotation={[0, -0.529, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Headphone_stand_bars.geometry}
        material={materials['Material.012']}
        position={[-0.772, 5.129, -4.662]}
        rotation={[0, -0.529, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HAWKTUAH_BARS.geometry}
        material={materials['Material.012']}
        position={[-0.742, 5.417, -4.654]}
        rotation={[0.039, -0.56, 1.594]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube001.geometry}
        material={materials['Material.028']}
        position={[1.022, 5.571, -5.974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Material.009']}
        position={[6.106, 4.594, -5.343]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials['Material.010']}
        position={[6.106, 4.594, -5.343]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials['Material.009']}
        position={[6.106, 6.115, -5.343]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials['Material.037']}
        position={[5.659, 5.372, -4.496]}
        rotation={[-1.561, 0.035, 1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube002.geometry}
        material={materials['Material.028']}
        position={[4.631, 5.571, -5.974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GPU_fan_1_middle.geometry}
        material={nodes.GPU_fan_1_middle.material}
        position={[5.698, 5.371, -4.495]}
        rotation={[-1.561, 0.035, 1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[5.691, 5.379, -4.428]}
        rotation={[-1.743, 0.025, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[5.7, 5.429, -4.46]}
        rotation={[-2.647, -0.106, 1.685]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[5.695, 5.425, -4.535]}
        rotation={[2.441, -0.312, 1.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[5.692, 5.37, -4.561]}
        rotation={[1.434, -0.336, 1.428]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[5.697, 5.31, -4.517]}
        rotation={[0.235, -0.156, 1.298]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[5.7, 5.321, -4.451]}
        rotation={[-0.597, 0.599, 1.376]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[5.7, 5.326, -5.018]}
        rotation={[-0.597, 0.599, 1.376]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[5.696, 5.315, -5.083]}
        rotation={[0.235, -0.156, 1.298]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[5.691, 5.375, -5.128]}
        rotation={[1.434, -0.336, 1.428]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[5.695, 5.431, -5.102]}
        rotation={[2.441, -0.312, 1.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[5.699, 5.434, -5.026]}
        rotation={[-2.647, -0.106, 1.685]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[5.691, 5.384, -4.994]}
        rotation={[-1.743, 0.025, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GPU_fan_2_middle.geometry}
        material={nodes.GPU_fan_2_middle.material}
        position={[5.698, 5.376, -5.062]}
        rotation={[-1.561, 0.035, 1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[5.69, 5.39, -5.543]}
        rotation={[-1.743, 0.025, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[5.698, 5.439, -5.575]}
        rotation={[-2.647, -0.106, 1.685]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[5.694, 5.436, -5.651]}
        rotation={[2.441, -0.312, 1.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[5.69, 5.38, -5.677]}
        rotation={[1.434, -0.336, 1.428]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[5.695, 5.321, -5.632]}
        rotation={[0.235, -0.156, 1.298]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[5.699, 5.331, -5.567]}
        rotation={[-0.597, 0.599, 1.376]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GPU_fan_3_middle.geometry}
        material={nodes.GPU_fan_3_middle.material}
        position={[5.697, 5.381, -5.61]}
        rotation={[-1.561, 0.035, 1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[5.697, 5.31, -4.517]}
        rotation={[0.235, -0.156, 1.298]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials['Material.037']}
        position={[6.166, 6.323, -5.417]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AIO_pipe_1.geometry}
        material={materials['Material.033']}
        position={[6.191, 6.21, -4.747]}
        rotation={[-2.146, 0.152, 1.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AIO_pipe_2.geometry}
        material={materials['Material.033']}
        position={[6.175, 6.34, -4.831]}
        rotation={[-2.146, 0.152, 1.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials['Material.015']}
        position={[3.826, 5.371, -5.681]}
        rotation={[0, 1.432, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunny_1_eyes.geometry}
        material={materials['Material.040']}
        position={[3.882, 5.59, -5.808]}
        rotation={[0, 1.432, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials['Material.009']}
        position={[3.751, 5.63, -5.688]}
        rotation={[-1.199, 1.028, 1.349]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={materials['Material.040']}
        position={[3.809, 5.495, -5.538]}
        rotation={[0.093, 1.28, -1.565]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert001.geometry}
        material={materials['Material.040']}
        position={[3.49, 5.455, -5.491]}
        rotation={[0.093, 1.28, -1.565]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials['Material.009']}
        position={[3.445, 5.561, -5.609]}
        rotation={[-1.199, 1.028, 1.349]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials['Material.015']}
        position={[3.503, 5.358, -5.603]}
        rotation={[0, 1.432, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunny_2_eyes.geometry}
        material={materials['Material.040']}
        position={[3.547, 5.529, -5.703]}
        rotation={[0, 1.432, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MOGGING.geometry}
        material={materials.Material}
        position={[0.951, 4.907, -4.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials.Material}
        position={[1.034, 4.916, -3.896]}
        rotation={[-0.778, 0.502, -1.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Seat.geometry}
        material={materials['Material.004']}
        position={[2.303, 3.029, -2.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials['Material.005']}
        position={[2.292, 1.237, -2.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_leg_1.geometry}
        material={materials['Material.006']}
        position={[2.294, 1.014, -2.193]}
        rotation={[0, -0.001, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_leg_2.geometry}
        material={materials['Material.006']}
        position={[2.168, 0.995, -2.474]}
        rotation={[-3.141, -1.345, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Headphone_front_pannel.geometry}
        material={materials['Material.028']}
        position={[-0.736, 4.94, -4.395]}
        rotation={[2.305, -0.981, 2.238]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Headphone_speaker_1.geometry}
        material={materials['Material.028']}
        position={[-0.712, 4.946, -4.457]}
        rotation={[2.306, -0.981, 2.238]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Speaker_1_stem.geometry}
        material={materials['Material.028']}
        position={[-0.754, 5.023, -4.442]}
        rotation={[2.642, -1.152, 2.537]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve012.geometry}
        material={materials['SVGMat.003']}
        position={[6.458, 9.115, -4.286]}
        rotation={[Math.PI / 2, -0.487, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane148.geometry}
        material={materials['Material.015']}
        position={[6.477, 9.151, -4.286]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane149.geometry}
        material={materials['Material.015']}
        position={[6.477, 9.151, -3.331]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane150.geometry}
        material={materials['Material.015']}
        position={[6.477, 9.151, -2.363]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane147.geometry}
        material={materials['Material.018']}
        position={[1.054, 0.779, 3.574]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane151.geometry}
        material={materials['Floor Plank.001']}
        position={[-5.286, 11.942, -6.695]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.024']}
        position={[6.69, 10.11, -5.394]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane153.geometry}
        material={materials['Material.030']}
        position={[-5.036, 0.145, -4.718]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Material.031']}
        position={[-5.049, 1.732, -4.702]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane155.geometry}
        material={materials['Material.036']}
        position={[-3.308, 4.256, -5.519]}
        rotation={[0, -1.392, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane112.geometry}
        material={materials['Material.017']}
        position={[2.872, 6.688, -5.563]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.219}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve013.geometry}
        material={materials['SVGMat.004']}
        position={[6.238, 8.814, -3.786]}
        rotation={[Math.PI / 2, -0.487, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve014.geometry}
        material={materials['SVGMat.005']}
        position={[6.277, 8.846, -1.977]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve015.geometry}
        material={materials['SVGMat.005']}
        position={[6.277, 8.846, -1.977]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve016.geometry}
        material={materials['SVGMat.005']}
        position={[6.277, 8.846, -1.977]}
        rotation={[Math.PI / 2, -0.487, -Math.PI / 2]}
      />
    </a.group>
  )
}

export default Room;